### ISSUE TITLE
Write "Testing instructions for application"

### ISSUE THREAD

**Issue by gmacario** [aquariophilie/axolotl#16]
_(share any specific info needed to access your project - responses will be not publicly visible)_

**NOTE**: This is a blocker for #1

**Comment by gmacario** [comment]
@gteti this issue is currently unassigned.

Since you are no longer a "fagiano" and you avoided to waste your time in useless tasks, would you agree to take care of this instead?

**Comment by gteti** [comment]
Since I'm tring to not be a "fagiano" anymore: I can't today because I have to go to the gym at 17:00 since I'm free from going to the airport.

**Comment by gmacario** [comment]
Testing instructions included in the submission to Codegeist 2021.
Please see https://github.com/aquariophilie/axolotl/blob/main/docs/2021-09-13-submit-project-axolotl.md#-testing-instructions-for-application
