### ISSUE TITLE
Develop the application for the deadline

### ISSUE THREAD

**Issue by gteti** [aquariophilie/axolotl#24]
I've tested the application at https://bitbucket.org/atlassian/forge-qr-code/src/master/

We should finalize the app before submission deadline expires.

**Comment by gmacario** [comment]
At least for what concerns the deadline for submission to Codegeist 2021 (#34), this task is completed.

@Raffone17 please notice that #29 is still open, and - as far as I know - nobody so far has been able to deploy the app in his own Confluence space. Please advise by commenting to #29 and/or opening related PRs
