### ISSUE TITLE
Write storyboard for the 2021-09-13 video

### ISSUE THREAD

**Issue by gmacario** [aquariophilie/axolotl#30]
Subtasks of #2

**Comment by gteti** [comment]
Storyboard:
- we open on a man and a woman opening up a bottle of wine to enjoy their evening together
- the man want to impress the woman and try to read the label to say some things about the bottle and wine content in it
- he finds out that there are few information there and don't know if he should search the web for hours or....
- USE our app!
- just by scanning the QR Code applied on the bottle you can access
- wine information, bottle handling and distribution

Another 2 cents of my fervid imagination! Please improve/change it however you like.

**Comment by gmacario** [comment]
@gteti your proposal looks quite nice and appealing.

As I heard no objections or further comments from @GGn0 and @Raffone17, as soon you write that down in a docs/2021-09-13-storyboard-for-codegest.md file and submit a PR I would consider this task completed

**Comment by gmacario** [comment]
Even though there is no linked PR to create file `docs/2021-09-013-storyboard-for-codegeist.md`, the simple fact that #2 and #7 have been completed makes me think #30 is done, too.

Closing
